/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import JSZip from 'jszip';

export const ARABIC_GAMEFONT_CSS = `/* Auto-generated by RPG Maker Game AI Translator */
@import url('https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800&family=Tajawal:wght@400;700&display=swap');

@font-face {
    font-family: GameFont;
    src: local('Cairo'),
         url('Cairo-Regular.woff2') format('woff2'),
         url('https://fonts.gstatic.com/s/cairo/v28/SLXfc1nY6HkvangtZmpQdkhzfH5lkSs2SgRjCAGMQ1z0hA.woff2') format('woff2'),
         url('mplus-1m-regular.ttf');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: GameFont;
    src: local('Cairo Bold'),
         url('Cairo-Bold.woff2') format('woff2'),
         url('https://fonts.gstatic.com/s/cairo/v28/SLXgc1nY6HkvangtZmpQdkhzfH5lkSs2SgRjCAGMQ1z0hAC5aIdU.woff2') format('woff2');
    font-weight: bold;
    font-style: normal;
}

/* Force Arabic font rendering on all game elements */
* {
    font-family: GameFont, 'Cairo', 'Tajawal', sans-serif !important;
}
`;

export const ARABIC_PLUGIN_JS = `//=============================================================================
// ArabicSupport.js
// RPG Maker MV / MZ Arabic Text & Font Fixer
//=============================================================================
/*:
 * @plugindesc Injects Cairo Arabic font and ensures correct rendering for Arabic translations.
 * @author RPG Maker Game AI Translator
 */
(function() {
    'use strict';
    // Ensure GameFont includes Cairo
    if (typeof Graphics !== 'undefined' && Graphics.loadFont) {
        Graphics.loadFont('GameFont', 'fonts/gamefont.css');
    }
    // Set standard window font name
    if (typeof Window_Base !== 'undefined') {
        var _Window_Base_standardFontFace = Window_Base.prototype.standardFontFace;
        Window_Base.prototype.standardFontFace = function() {
            return "GameFont, 'Cairo', 'Tajawal', sans-serif";
        };
    }
    console.log("[RPG Maker AI Translator] Arabic Font & Text support initialized.");
})();
`;

/**
 * Checks if the game files have Arabic font support, and injects it if missing.
 */
export async function injectArabicFontIntoZip(zip: JSZip): Promise<{
  modifiedFiles: string[];
  addedFiles: string[];
}> {
  const modifiedFiles: string[] = [];
  const addedFiles: string[] = [];

  // 1. Check or inject fonts/gamefont.css
  const existingGameFontCss = zip.file('fonts/gamefont.css') || zip.file('css/gamefont.css');
  if (existingGameFontCss) {
    const origPath = existingGameFontCss.name;
    const content = await existingGameFontCss.async('string');
    // If not already modified
    if (!content.includes('Cairo') && !content.includes('Tajawal')) {
      zip.file(origPath, ARABIC_GAMEFONT_CSS);
      modifiedFiles.push(origPath);
    }
  } else {
    // Add fonts/gamefont.css
    zip.file('fonts/gamefont.css', ARABIC_GAMEFONT_CSS);
    addedFiles.push('fonts/gamefont.css');
  }

  // 2. Check index.html to inject font CDN link
  const indexHtmlFile = zip.file('index.html');
  if (indexHtmlFile) {
    let indexHtml = await indexHtmlFile.async('string');
    if (!indexHtml.includes('fonts.googleapis.com/css2?family=Cairo')) {
      const fontTag = `\n    <!-- Arabic Font Injected by RPG Maker AI Translator -->\n    <link rel="preconnect" href="https://fonts.googleapis.com">\n    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700;800&family=Tajawal:wght@400;700&display=swap" rel="stylesheet">\n    <style>body, canvas { font-family: 'Cairo', 'Tajawal', sans-serif !important; }</style>\n`;
      if (indexHtml.includes('</head>')) {
        indexHtml = indexHtml.replace('</head>', `${fontTag}</head>`);
      } else {
        indexHtml = fontTag + indexHtml;
      }
      zip.file('index.html', indexHtml);
      modifiedFiles.push('index.html');
    }
  }

  // 3. Inject ArabicSupport.js plugin if js/plugins exists
  const hasPluginsDir = Object.keys(zip.files).some((p) => p.startsWith('js/plugins/'));
  if (hasPluginsDir && !zip.file('js/plugins/ArabicSupport.js')) {
    zip.file('js/plugins/ArabicSupport.js', ARABIC_PLUGIN_JS);
    addedFiles.push('js/plugins/ArabicSupport.js');

    // Also inject into js/plugins.js if exists so the engine activates it
    const pluginsJs = zip.file('js/plugins.js');
    if (pluginsJs) {
      try {
        let pContent = await pluginsJs.async('string');
        if (!pContent.includes('ArabicSupport')) {
          pContent = pContent.replace(
            /(\$plugins\s*=\s*\[)/,
            `$1\n{"name":"ArabicSupport","status":true,"description":"Arabic Font and Layout Fix","parameters":{}},`
          );
          zip.file('js/plugins.js', pContent);
          modifiedFiles.push('js/plugins.js');
        }
      } catch (e) {
        console.warn("Could not patch js/plugins.js:", e);
      }
    }
  }

  return { modifiedFiles, addedFiles };
}
